/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.cad_servico;
import View.Login;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author CASA
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuServico = new javax.swing.JMenu();
        MenuNovoServico = new javax.swing.JMenuItem();
        MenuPesquisaServico = new javax.swing.JMenuItem();
        MenuHistoricoServico = new javax.swing.JMenuItem();
        MenuAdministrativo = new javax.swing.JMenu();
        MenuClientes = new javax.swing.JMenuItem();
        MenuTipoServico = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DASHBOARD");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        MenuServico.setText("SERVIÇO");

        MenuNovoServico.setText("NOVO");
        MenuNovoServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuNovoServicoMouseClicked(evt);
            }
        });
        MenuNovoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNovoServicoActionPerformed(evt);
            }
        });
        MenuServico.add(MenuNovoServico);

        MenuPesquisaServico.setText("PESQUISAR SERVIÇO");
        MenuPesquisaServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPesquisaServicoActionPerformed(evt);
            }
        });
        MenuServico.add(MenuPesquisaServico);

        MenuHistoricoServico.setText("HISTÓRICO DE SERVIÇOS");
        MenuServico.add(MenuHistoricoServico);

        jMenuBar1.add(MenuServico);

        MenuAdministrativo.setText("ADMINISTRATIVO");

        MenuClientes.setText("CLIENTES");
        MenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuClientesActionPerformed(evt);
            }
        });
        MenuAdministrativo.add(MenuClientes);

        MenuTipoServico.setText("TIPOS DE SERVIÇOS");
        MenuTipoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTipoServicoActionPerformed(evt);
            }
        });
        MenuAdministrativo.add(MenuTipoServico);

        jMenuItem1.setText("TIPO DE PAGAMENTO");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuAdministrativo.add(jMenuItem1);

        jMenuItem2.setText("TIPO DE PRODUTO");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuAdministrativo.add(jMenuItem2);

        jMenuBar1.add(MenuAdministrativo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuTipoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTipoServicoActionPerformed

        try {
            cons_tipo_servico consTPS;
            consTPS = new cons_tipo_servico();

            consTPS.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_MenuTipoServicoActionPerformed

    private void MenuPesquisaServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPesquisaServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuPesquisaServicoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:

        Login login = new Login();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void MenuNovoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNovoServicoActionPerformed
        cad_servico cad_servico = null;
        try {
            cad_servico = new cad_servico();
            cad_servico.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuNovoServicoActionPerformed

    private void MenuNovoServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuNovoServicoMouseClicked
        // TODO add your handling code here:
        cad_servico cad_servico = null;
        try {
            cad_servico = new cad_servico();
            cad_servico.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MenuNovoServicoMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        try {
            cons_tipo_pagamento consTPP;
            consTPP = new cons_tipo_pagamento();

            consTPP.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuClientesActionPerformed
        cons_cliente consTPC = null;
        try {
            consTPC = new cons_cliente();
            consTPC.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_MenuClientesActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            cons_tipo_produto consTPPROD;
            consTPPROD = new cons_tipo_produto();
            consTPPROD.setVisible(true);

        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAdministrativo;
    private javax.swing.JMenuItem MenuClientes;
    private javax.swing.JMenuItem MenuHistoricoServico;
    private javax.swing.JMenuItem MenuNovoServico;
    private javax.swing.JMenuItem MenuPesquisaServico;
    private javax.swing.JMenu MenuServico;
    private javax.swing.JMenuItem MenuTipoServico;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
