/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import View.cad_servico;
import View.Login;
/**
 *
 * @author CASA
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuServico = new javax.swing.JMenu();
        MenuNovoServico = new javax.swing.JMenuItem();
        MenuPesquisaServico = new javax.swing.JMenuItem();
        MenuHistoricoServico = new javax.swing.JMenuItem();
        MenuAdministrativo = new javax.swing.JMenu();
        MenuClientes = new javax.swing.JMenuItem();
        MenuTipoServico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        MenuServico.setText("SERVIÇO");

        MenuNovoServico.setText("NOVO");
        MenuNovoServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuNovoServicoMouseClicked(evt);
            }
        });
        MenuNovoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNovoServicoActionPerformed(evt);
            }
        });
        MenuServico.add(MenuNovoServico);

        MenuPesquisaServico.setText("PESQUISAR SERVIÇO");
        MenuPesquisaServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPesquisaServicoActionPerformed(evt);
            }
        });
        MenuServico.add(MenuPesquisaServico);

        MenuHistoricoServico.setText("HISTÓRICO DE SERVIÇOS");
        MenuServico.add(MenuHistoricoServico);

        jMenuBar1.add(MenuServico);

        MenuAdministrativo.setText("ADMINISTRATIVO");

        MenuClientes.setText("CLIENTES");
        MenuAdministrativo.add(MenuClientes);

        MenuTipoServico.setText("TIPOS DE SERVIÇOS");
        MenuTipoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTipoServicoActionPerformed(evt);
            }
        });
        MenuAdministrativo.add(MenuTipoServico);

        jMenuBar1.add(MenuAdministrativo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jButton1)
                .addContainerGap(419, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jButton1)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuTipoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTipoServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuTipoServicoActionPerformed

    private void MenuPesquisaServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPesquisaServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuPesquisaServicoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
                
        Login login = new Login();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void MenuNovoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNovoServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuNovoServicoActionPerformed

    private void MenuNovoServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuNovoServicoMouseClicked
        // TODO add your handling code here:
        cad_servico cad_servico = new cad_servico();
        cad_servico.setVisible(true);
    }//GEN-LAST:event_MenuNovoServicoMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
  cad_servico cad_servico = new cad_servico();
        cad_servico.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAdministrativo;
    private javax.swing.JMenuItem MenuClientes;
    private javax.swing.JMenuItem MenuHistoricoServico;
    private javax.swing.JMenuItem MenuNovoServico;
    private javax.swing.JMenuItem MenuPesquisaServico;
    private javax.swing.JMenu MenuServico;
    private javax.swing.JMenuItem MenuTipoServico;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
